POST http://pomodoro.com:8000/auth/token/login/
Content-Type: application/x-www-form-urlencoded

username=rampage&password=bookOrShelf


> {% client.global.set("auth_token", response.body.auth_token); %}